server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sports-center
    username: root
    password: password
  application:
    name: SportsCenter
  jobs:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

